import os
 
base173l = "python makeShapeCardsSusy.py  RunII_SUSY_EWK/2017/4l/mca_ewkino_v5.txt RunII_SUSY_EWK/2017/4l/cuts_4l.txt --FFasts {P}/puWeight/  '[VAR]' '[BINS]' RunII_SUSY_EWK/systs/systs_wz17.txt --tree treeProducerSusyMultilepton -P /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ -P /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2017_signals/ --FFulls {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderEWK/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SUSY_EWK/functionsEWKcorr.cc --plotgroup data_fakes+=.*promptsub.* --neglist .*promptsub.* --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --neg -W 'puWeight*($MC{bTagWeightDeepCSVT_nom} $FASTSIM{bTagWeightDeepCSVT})*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*getLeptonSF_v4(0,0,2017,LepSel_pt[3],LepSel_eta[3],LepSel_pdgId[3]))' --xp .*VH.* --obj Events -j 32 -f  -l 41.5  -E [SRCUT]  [EXCLUDERS] -o [OCARD] --od [OD] "

allSignals = ['sig_TChiWZ.*', 'sig_TChiWH.*', 'sig_TChiZZ.*', 'sig_TChiHH.*', 'sig_TChiHZ.*', 'sig_TChiSlep.*', 'sig_TChiTESlep.*', 'sig_TChiStau.*']
vetoSignals = ['sig_TChiWZ.*', 'sig_TChiSlep.*',  'sig_TChiTESlep.*', 'sig_TChiWH.*', 'sig_TChiStau.*']
varsandbins = {'SR4lGplot(mt2davis_mass(pt_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), eta_2(LepSel_conePt[mll_i1[0]],LepSel_eta[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_mass[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_eta[mll_i2[0]],LepSel_phi[mll_i2[0]],LepSel_mass[mll_i2[0]]), phi_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), pt_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), eta_2(LepSel_conePt[mll_i1[1]],LepSel_eta[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_mass[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_eta[mll_i2[1]],LepSel_phi[mll_i2[1]],LepSel_mass[mll_i2[1]]), phi_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), METFixEE2017_pt_nom, METFixEE2017_phi_nom, 91.17), METFixEE2017_pt_nom, mass_2(LepSel_pt[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_pt[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 2)]))' : '5, 0.5,5.5'} 
oCARD = 'SR4lG_2017'
oDir  = {'SR4lGplot(mt2davis_mass(pt_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), eta_2(LepSel_conePt[mll_i1[0]],LepSel_eta[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_mass[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_eta[mll_i2[0]],LepSel_phi[mll_i2[0]],LepSel_mass[mll_i2[0]]), phi_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), pt_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), eta_2(LepSel_conePt[mll_i1[1]],LepSel_eta[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_mass[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_eta[mll_i2[1]],LepSel_phi[mll_i2[1]],LepSel_mass[mll_i2[1]]), phi_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), METFixEE2017_pt_nom, METFixEE2017_phi_nom, 91.17), METFixEE2017_pt_nom, mass_2(LepSel_pt[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_pt[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 2)]))' :'cards_4lG17_SRnew'}
SRCUT = "SR4lG" 

for sigs in allSignals:
  if sigs in vetoSignals: continue
  for vb in varsandbins:
     excluders = ""
     for v in allSignals:
       if v != sigs:
          excluders = excluders + " --xp " + v
     command = base173l.replace("[VAR]", vb).replace("[BINS]",varsandbins[vb]).replace("[SRCUT]",SRCUT).replace("[OCARD]",oCARD).replace("[OD]", oDir[vb]+ sigs.replace("sig_","").replace(".*","")).replace("[EXCLUDERS]", excluders)
     print command
     os.system("sbatch -c 32 -p short -J" + sigs + " --wrap \"" + command.replace("$","\$") + "\"")

