import os

base = "python makeShapeCardsSusy.py  RunII_SUSY_EWK/2016/4l/mca_ewkino_v5.txt RunII_SUSY_EWK/2016/4l/cuts_4l.txt 'SR4lGplot(mt2davis_mass(pt_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), eta_2(LepSel_conePt[mll_i1[0]],LepSel_eta[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_mass[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_eta[mll_i2[0]],LepSel_phi[mll_i2[0]],LepSel_mass[mll_i2[0]]), phi_2(LepSel_conePt[mll_i1[0]],LepSel_phi[mll_i1[0]],LepSel_conePt[mll_i2[0]],LepSel_phi[mll_i2[0]]), pt_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), eta_2(LepSel_conePt[mll_i1[1]],LepSel_eta[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_mass[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_eta[mll_i2[1]],LepSel_phi[mll_i2[1]],LepSel_mass[mll_i2[1]]), phi_2(LepSel_conePt[mll_i1[1]],LepSel_phi[mll_i1[1]],LepSel_conePt[mll_i2[1]],LepSel_phi[mll_i2[1]]), MET_pt_nom, MET_phi_nom, 91.16), MET_pt_nom, mass_2(LepSel_pt[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 1)], LepSel_pt[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_eta[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_phi[unused4(mll_i1[0], mll_i2[0], 2)], LepSel_mass[unused4(mll_i1[0], mll_i2[0], 2)]))' '5, 0.5,5.5' RunII_SUSY_EWK/systs/systs_wz16.txt --tree treeProducerSusyMultilepton -P /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ -P /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_signals/ --FFasts {P}/puWeight/ --FFulls {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderEWK/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SUSY_EWK/functionsEWKcorr.cc --plotgroup data_fakes+=.*promptsub.* --neglist .*promptsub.* --neg -W 'puWeight*($MC{bTagWeightDeepCSVT_nom} $FASTSIM{bTagWeightDeepCSVT})*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*getLeptonSF_v4(0,0,2016,LepSel_pt[3],LepSel_eta[3],LepSel_pdgId[3]))' -X SRevent -A  alwaystrue lepMVA 'allTight(LepGood_mvaTTH[iL_Mini[0]],LepGood_mvaTTH[iL_Mini[1]],LepGood_mvaTTH[iL_Mini[2]],LepGood_pdgId[iL_Mini[0]],LepGood_pdgId[iL_Mini[1]],LepGood_pdgId[iL_Mini[2]], [CUT1],[CUT2])' -p prompt.*  -p fakes.* -p sig_TChiZZ_400_1.* -p sig_TChiHZ_175_1.*  --obj Events -j 8 -f  -l 35.9  -E SR4lG  -o mvael[TAG1]mvamu[TAG2] --od testleptonMVA16_4l --asimov"

for i in range(20):
  for j in range(20):
    x = -1. + 0.1*i
    y = -1. + 0.1*j
    #print base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(x).replace("-","m"))
    #os.system("sbatch -c 8 -p batch -J" + " --wrap \"" + base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(x).replace("-","m")) + "\"")
    print "sbatch -c 8 -p batch " + " --wrap \"" + base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(y).replace("-","m")).replace("$","\$") + "\""
