import os
base = "python makeShapeCardsSusy.py RunII_SUSY_EWK/2016/3l/mca_ewkino_v5.txt RunII_SUSY_EWK/2016/3l/cuts_3l.txt 'SR3lA(-1, -1, mll_3l, mT_3l, MET_pt_nom)' '44,0.5,44.5' RunII_SUSY_EWK/systs/systs_wz16.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/ --FFasts {P}/puWeight/ --FFulls {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderEWK/ --Fs {P}/trigger_2016/  --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SUSY_EWK/functionsEWKcorr.cc   --plotgroup data_fakes+=.*promptsub.* --neglist .*promptsub.* --neg -W 'puWeight*($MC{bTagWeightDeepCSVT_nom} $FASTSIM{bTagWeightDeepCSVT})*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))' --obj Events -j 8 -f  -l 35.9  -E SR3lA  -p prompt.* -p conv.* -p data.* -p fakes.* -p 'sig_TChiWZ_200_110.*' -p 'sig_TChiWZ_500_1.*' -p 'sig_TChiWZ_150_100.*'  -X SRevent -A  alwaystrue lepMVA 'allTight(LepGood_mvaTTH[iL_Mini[0]],LepGood_mvaTTH[iL_Mini[1]],LepGood_mvaTTH[iL_Mini[2]],LepGood_pdgId[iL_Mini[0]],LepGood_pdgId[iL_Mini[1]],LepGood_pdgId[iL_Mini[2]], [CUT1],[CUT2])' -o mvael[TAG1]mvamu[TAG2] --od testleptonMVA16_3l"

for i in range(20):
  for j in range(20):
    x = -1. + 0.1*i
    y = -1. + 0.1*j
    #print base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(x).replace("-","m"))
    #os.system("sbatch -c 8 -p batch -J" + " --wrap \"" + base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(x).replace("-","m")) + "\"")
    print "sbatch -c 8 -p batch " + " --wrap \"" + base.replace("[CUT1]", str(x)).replace("[CUT2]", str(y)).replace("[TAG1]", str(x).replace("-","m")).replace("[TAG2]", str(y).replace("-","m")).replace("$","\$") + "\""
