python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/lepton-fr/mca-lepfr-mc.txt -L 5TeV/functions5TeV.cc --ytitle 'Trigger efficiency' --ytitle 'Fake rate' 5TeV/lepton-fr/fr_cuts.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Apr30_FR/ --FMCs {P}/0_jmeUnc_v1  --Fs {P}/1_recleaner_v2   5TeV/lepton-fr/make_fake_rates_sels.txt  5TeV/lepton-fr/make_fake_rates_xvars.txt -E ^mu --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.2 2.0  --yrange 0.01 0.4 -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20May11_FakeRates/mc/fakerates_mu.root --sP pt_fine --sP pt_match --sP ptJ_coarse --sP mtW1 --sP wz_tight 

python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/lepton-fr/mca-lepfr-mc.txt object-studies/lepton-perlep.txt -L 5TeV/functions5TeV.cc  --ytitle 'Fake rate'    -P /eos/cms/store/group/phys_muon/folguera/5TeV_Apr30_FR/ 5TeV/lepton-fr/make_fake_rates_sels.txt 5TeV/lepton-fr/make_fake_rates_xvars.txt --groupBy cut 

--sP wz_tight  --legend=TR --showRatio --ratioRange 0.00 1.99   --yrange 0 0.35  -A pt20 mll 'nLepGood == 1' -A pt20 den 'LepGood_sip3d < 8' -A pt20 mmuid 'LepGood_mediumId>=0' -A pt20 mpt 'LepGood_pt > 5'  -A pt20 jet 'LepGood_awayJet_pt >= 30' --sP 'pt_fine' --sp TT_red   --xcut 10 999 --xline 15  -p TT_red -o //mu_lbin_wztight_recJet30_eta_00_12.root    -R pt20 eta 'abs(LepGood_eta)<1.2'    -j 8


python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/lepton-fr/mca-lepfr-mc.txt -L 5TeV/functions5TeV.cc --ytitle 'Trigger efficiency' --ytitle 'Fake rate' 5TeV/lepton-fr/fr_cuts.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Apr30_FR/ --FMCs {P}/0_jmeUnc_v1  --Fs {P}/1_recleaner_v2   5TeV/lepton-fr/make_fake_rates_sels.txt  5TeV/lepton-fr/make_fake_rates_xvars.txt -E ^el --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.2 2.0  --yrange 0.01 0.4 -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20May11_FakeRates/mc/fakerates_el.root --sP pt_fine --sP pt_match --sP ptJ_coarse --sP mtW1 --sP wz_tight 

python mcEfficiencies.py  --s2v --tree NanoAOD ttH-multilepton/lepton-fr/lepton-mca-frstudies.txt object-studies/lepton-perlep.txt -L ttH-multilepton/functionsTTH.cc --Fs {P}/1_frFriends_v1 --mcc ttH-multilepton/mcc-eleIdEmu2.txt   --ytitle 'Fake rate'    -P /eos/cms/store/cmst3/group/tthlep/gpetrucc/TREES_ttH_FR_nano_v5/2016 ttH-multilepton/lepton-fr/make_fake_rates_sels.txt ttH-multilepton/lepton-fr/make_fake_rates_xvars.txt --groupBy cut --sP mvaPt_090i  --legend=TR --showRatio --ratioRange 0.00 1.99   --yrange 0 0.35  -A pt20 mll 'nLepGood == 1' -A pt20 den 'LepGood_sip3d < 8 && LepGood_jetBTagDeepFlav < 0.3093 && (LepGood_mvaTTH > 0.90 || (abs(LepGood_pdgId)==13 && LepGood_jetBTagDeepFlav < 0.0614) || (abs(LepGood_pdgId)==11 && LepGood_jetBTagDeepFlav < 0.0614))' -A pt20 ptfden '(LepGood_mvaTTH > 0.90 || 1/(1+LepGood_jetRelIso) > 0.60)'  -I mu -A pt20 convveto 'LepGood_convVeto && LepGood_lostHits == 0 && LepGood_tightCharge >= 0 && ' -A pt20 elpt 'LepGood_pt > 7'   -A pt20 jet 'LepGood_awayJet_pt >= 30' --sP 'ptJI90_mvaPt090_zcoarse2' --sp TT_red --xcut 10 30  -p TT_red,TT_redNC,Z3l_red,Z3l_red_80,Z3l_redNC,Z3l_red_m3l  -o plots/104X/ttH/lepMVA/v1.1/fr-mc/2016//el_ttz3lplus_wp090iv01f60E3_recJet30_eta_15_25.root -R pt20 eta 'abs(LepGood_eta)>1.479'    -j 8

