python mcEfficiencies.py --s2v -tree NanAOD 5TeV/mca-wz-3l-mcdata.txt 5TeV/wz_3l.txt --FMCs {P}/0_jmeUnc_v1 --FMCs {P}/0_weights_v1 --Fs {P}/1_recleaner_v2 --Fs {P}/2_eventVars_v3 --ytitle 'Efficiency' -P /eos/cms/store/group/phys_muon/folguera/5TeV_Mar23/ 5TeV/lepton-fr/make_trigger_eff_sels.txt  5TeV/lepton-fr/make_trigger_eff_xvars.txt 
-L 5TeV/functions5TeV.cc --mcc 5TeV/lepchoice-FO.txt --groupBy cut --sP pt_fine --legend=TR --showRatio --ratioRange 0.00 1.99   --yrange 0 0.35 -X ^trigger --sp WZ -p WZ -o //trigger_eff.root  -j 8


python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/mca-wz-3l-mcdata.txt -L 5TeV/functions5TeV.cc --mcc 5TeV/lepchoice-FO.txt --ytitle 'Trigger efficiency' 5TeV/trigger-eff/cuts_trigger_eff_wz_3l.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Mar23/ --FMCs {P}/0_jmeUnc_v1 --FDs {P}/0_jmeUncData_v1 --FMCs {P}/0_weights_v1 --Fs {P}/1_recleaner_v2 --Fs {P}/2_eventVars_v3 5TeV/trigger-eff/make_trigger_eff_sels.txt 5TeV/trigger-eff/make_trigger_eff_xvars.txt --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.9 1.05  --yrange 0.8 1.2  -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20Apr27_TriggerEff/wz/3l/triggers.root -p WZ --sP lep1_pt --sP lep_3l_pt --sP lep2_pt --sP lep3_pt --sP tot_weight --sP single --sP double --sP cocktail --sP MuEle17


python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/mca-wz-2lss-mcdata.txt -L 5TeV/functions5TeV.cc --mcc 5TeV/lepchoice-FO.txt --ytitle 'Trigger efficiency' 5TeV/trigger-eff/cuts_trigger_eff_wz_2lss.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Mar23/ --FMCs {P}/0_jmeUnc_v1 --FDs {P}/0_jmeUncData_v1 --FMCs {P}/0_weights_v1 --Fs {P}/1_recleaner_v2 --Fs {P}/2_eventVars_v3 5TeV/trigger-eff/make_trigger_eff_sels.txt 5TeV/trigger-eff/make_trigger_eff_xvars.txt --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.9 1.05  --yrange 0.8 1.2  -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20Apr27_TriggerEff/wz/2lss/triggers.root -p WZ --sP lep1_pt --sP lep_2l_pt --sP lep2_pt  --sP tot_weight --sP single --sP double --sP cocktail --sP MuEle17


python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/mca-ww-mcdata.txt -L 5TeV/functions5TeV.cc --mcc 5TeV/lepchoice-FO.txt --ytitle 'Trigger efficiency' 5TeV/trigger-eff/cuts_trigger_eff_ww.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Mar23/ --FMCs {P}/0_jmeUnc_v1 --FDs {P}/0_jmeUncData_v1 --FMCs {P}/0_weights_v1 --Fs {P}/1_recleaner_v2 --Fs {P}/2_eventVars_v3 5TeV/trigger-eff/make_trigger_eff_sels.txt 5TeV/trigger-eff/make_trigger_eff_xvars.txt --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.9 1.05  --yrange 0.8 1.2  -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20Apr27_TriggerEff/ww/triggers.root -p WW --sP lep1_pt --sP lep_2l_pt --sP lep2_pt  --sP tot_weight --sP single --sP double --sP cocktail --sP MuEle17


python mcEfficiencies.py  --s2v --tree NanoAOD 5TeV/mca-ttbar-mcdata.txt -L 5TeV/functions5TeV.cc --mcc 5TeV/lepchoice-FO.txt --ytitle 'Trigger efficiency' 5TeV/trigger-eff/cuts_trigger_eff_ttbar.txt -P /eos/cms/store/group/phys_muon/folguera/5TeV_Mar23/ --FMCs {P}/0_jmeUnc_v1 --FDs {P}/0_jmeUncData_v1 --FMCs {P}/0_weights_v1 --Fs {P}/1_recleanerTight_v2  5TeV/trigger-eff/make_trigger_eff_sels.txt 5TeV/trigger-eff/make_trigger_eff_xvars.txt --groupBy cut --split-factor=-1 -f -j 12 --legend=BR --showRatio --ratioRange 0.9 1.05  --yrange 0.8 1.2  -o /afs/cern.ch/user/f/folguera/www/private/5TeV/20Apr27_TriggerEff/ttbar/triggers.root -p TT --sP lep1_pt --sP lep_2l_pt --sP lep2_pt  --sP tot_weight --sP single --sP double --sP cocktail --sP MuEle17
