python mcPlots.py RunII_SM_WZ/2016/mca_wz.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 3.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/wz --showRatio -E SRWZ --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2016/mca_wz.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 3.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/crconv --showRatio -E SRCr-Conv --sP mtW3l --sP flavor3l --sP charge3l

python mcPlots.py RunII_SM_WZ/2016/mca_wz.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 3.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*getLeptonSF_v4(0,0,2016,LepGood_pt[3],LepGood_eta[3],LepGood_pdgId[3])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/crzz --showRatio -E SRCr-ZZ --sP mtW3l --sP flavor3l --sP charge3l

python mcPlots.py RunII_SM_WZ/2016/mca_wz.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 3.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/crtop --showRatio -E SRCr-top --sP mtW3l --sP flavor3l --sP charge3l




python mcPlots.py RunII_SM_WZ/2017/mca_wz.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2017_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2017,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2017,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2017,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 41.2 -f --pdir /nfs/fanae/user/joanrs/www/2017/crtop --showRatio -E CRTT --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2017/mca_wz.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2017_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2017,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2017,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2017,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*getLeptonSF_v4(0,0,2017,LepGood_pt[3],LepGood_eta[3],LepGood_pdgId[3])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 41.2 -f --pdir /nfs/fanae/user/joanrs/www/2017/crzz --showRatio -E CRZZ --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2017/mca_wz.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2017_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2017,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2017,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2017,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 41.2 -f --pdir /nfs/fanae/user/joanrs/www/2017/crconv --showRatio -E CRconv --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2017/mca_wz.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2017_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2017,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2017,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2017,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 41.2 -f --pdir /nfs/fanae/user/joanrs/www/2017/wz --showRatio -E SRWZ --sP mtW3l --sP flavor3l --sP charge3l






python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crtop --showRatio -E CRTT --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/wz --showRatio -E SRWZ --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crconv --showRatio -E CRconv --sP mtW3l --sP flavor3l --sP charge3l


python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0 2.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*getLeptonSF_v4(0,0,2018,LepGood_pt[3],LepGood_eta[3],LepGood_pdgId[3])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crzz --showRatio -E CRZZ --sP mtW3l --sP flavor3l --sP charge3l


