python mcPlots.py RunII_SM_WZ/2016/mca_pol.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/bosonPolarization/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 0.6 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/POL/wz/ --showRatio -E SRWZ  --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen total --noErrorBandOnRatio -E cIn


python mcPlots.py RunII_SM_WZ/2016/mca_pol.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/bosonPolarization/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 0.6 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/POL/crtop/ --showRatio -E SRCr-top  --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen total --noErrorBandOnRatio -E cIn


python mcPlots.py RunII_SM_WZ/2016/mca_pol.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/bosonPolarization/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 0.6 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/POL/crconv/ --showRatio -E SRCr-Conv --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen total --noErrorBandOnRatio -E cIn


python mcPlots.py RunII_SM_WZ/2016/mca_pol.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2016_skimWZ/ {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/bosonPolarization/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2016/mcc_triggerdefs.txt --maxRatioRange 0. 0.6 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2016,LepGood_pt[0],LepGood_eta[0],LepGood_pdgId[0])*getLeptonSF_v4(0,0,2016,LepGood_pt[1],LepGood_eta[1],LepGood_pdgId[1])*getLeptonSF_v4(0,0,2016,LepGood_pt[2],LepGood_eta[2],LepGood_pdgId[2])*getLeptonSF_v4(0,0,2016,LepGood_pt[3],LepGood_eta[3],LepGood_pdgId[3])*puWeight*bTagWeightDeepCSVT*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 6 -l 35.9 -f --pdir /nfs/fanae/user/joanrs/www/2016/POL/crzz/ --showRatio -E SRCr-ZZ  --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --
ratioDen total --noErrorBandOnRatio -E cIn



