python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0.6 1.4  --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crtop --showRatio -E CRTT


python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0.6 1.4  --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/wz --showRatio -E SRWZ


python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0.6 1.4  --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crconv --showRatio -E CRconv

python mcPlots.py RunII_SM_WZ/2018/mca_wz.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv4_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM_v2/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagWeights/ --FMCs {P}/pileUpWeight/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0.6 1.4  --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W 'getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2])*getLeptonSF_v4(0,0,2018,LepSel_pt[3],LepSel_eta[3],LepSel_pdgId[3])*vtxWeight2018Nominal*bTagWeightDeepCSVT' --obj Events --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt -j 6 -l 58.9 -f --pdir /nfs/fanae/user/joanrs/www/2018/crzz --showRatio -E CRZZ

