# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-01-01 [yyyy-m-d] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
json = os.environ['CMSSW_BASE']+'/src/CMGTools/TTHAnalysis/cfg/Cert_Collisions2022_355100_362760_Golden.json'
# ------ Muon dataset
Muon_Run2022C_0 = kreator.makeDataComponentFromLocal('Muon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022C-PromptNanoAODv10-v1/221013_080134/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_0 = kreator.makeDataComponentFromLocal('Muon_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10-v1/221013_080353/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_1 = kreator.makeDataComponentFromLocal('Muon_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10_v1-v1/221013_080611/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022E_0 = kreator.makeDataComponentFromLocal('Muon_Run2022E', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/31oct2022_Muon_Run2022E-PromptNanoAODv10_v1-v3/221031_102034/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022F_0 = kreator.makeDataComponentFromLocal('Muon_Run2022F', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/data2022F_28nov2022_Muon_Run2022F-PromptNanoAODv10_v1-v2/221128_142900/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022G_0 = kreator.makeDataComponentFromLocal('Muon_Run2022G', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/run2022G_9dec2022_Muon_Run2022G-PromptNanoAODv10_v1-v1/221209_083743/0000', '', '.*root', 2022, [], json = json)
Muon = [Muon_Run2022C_0, Muon_Run2022D_0, Muon_Run2022D_1, Muon_Run2022E_0, Muon_Run2022F_0, Muon_Run2022G_0]

# ------ SingleMuon dataset
SingleMuon_Run2022C_0 = kreator.makeDataComponentFromLocal('SingleMuon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//SingleMuon/27sep2022_data_SingleMuon_Run2022C-PromptNanoAODv10-v1/221013_075910/0000', '', '.*root', 2022, [], json = json)
SingleMuon = [SingleMuon_Run2022C_0]

# ------ DoubleMuon dataset
DoubleMuon_Run2022C_0 = kreator.makeDataComponentFromLocal('DoubleMuon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//DoubleMuon/27sep2022_data_DoubleMuon_Run2022C-PromptNanoAODv10-v1/221013_075640/0000', '', '.*root', 2022, [], json = json)
DoubleMuon = [DoubleMuon_Run2022C_0]

# ------ MET dataset
MET_Run2022C_0 = kreator.makeDataComponentFromLocal('MET_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MET/27sep2022_data_MET_Run2022C-PromptNanoAODv10-v1/221013_080830/0000', '', '.*root', 2022, [], json = json)
MET = [MET_Run2022C_0]

# ------ JetHT dataset
JetHT_Run2022C_0 = kreator.makeDataComponentFromLocal('JetHT_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetHT/27sep2022_data_JetHT_Run2022C-PromptNanoAODv10-v1/221013_081051/0000', '', '.*root', 2022, [], json = json)
JetHT = [JetHT_Run2022C_0]

# ------ EGamma dataset
EGamma_Run2022C_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022C-PromptNanoAODv10-v2/221013_082717/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10-v2/221013_082934/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_1 = kreator.makeDataComponentFromLocal('EGamma_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10_v1-v1/221013_083152/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022E_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022E', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/data22EF_26oct2022_EGamma_Run2022E-PromptNanoAODv10_v1-v2/221026_154418/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022F_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022F', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/data2022F_28nov2022_EGamma_Run2022F-PromptNanoAODv10_v1-v2/221128_143539/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022F_1 = kreator.makeDataComponentFromLocal('EGamma_Run2022F', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/data2022F_28nov2022_EGamma_Run2022F-PromptNanoAODv10_v1-v2/221201_133821/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022G_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022G', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/run2022G_9dec2022_EGamma_Run2022G-PromptNanoAODv10_v1-v1/221209_084312/0000', '', '.*root', 2022, [], json = json)
EGamma = [EGamma_Run2022C_0, EGamma_Run2022D_0, EGamma_Run2022D_1, EGamma_Run2022E_0, EGamma_Run2022F_0, EGamma_Run2022F_1, EGamma_Run2022G_0]

# ------ JetMET dataset
JetMET_Run2022C_0 = kreator.makeDataComponentFromLocal('JetMET_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/27sep2022_data_JetMET_Run2022C-PromptNanoAODv10-v1/221013_081310/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022D_0 = kreator.makeDataComponentFromLocal('JetMET_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/27sep2022_data_JetMET_Run2022D-PromptNanoAODv10-v2/221013_081534/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022D_1 = kreator.makeDataComponentFromLocal('JetMET_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/27sep2022_data_JetMET_Run2022D-PromptNanoAODv10_v1-v1/221013_081755/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022E_0 = kreator.makeDataComponentFromLocal('JetMET_Run2022E', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/data22EF_26oct2022_JetMET_Run2022E-PromptNanoAODv10_v1-v3/221026_153455/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022F_0 = kreator.makeDataComponentFromLocal('JetMET_Run2022F', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/data2022F_28nov2022_JetMET_Run2022F-PromptNanoAODv10_v1-v2/221128_143114/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022G_0 = kreator.makeDataComponentFromLocal('JetMET_Run2022G', '', '/pool/phedex/nanoAODv10/27sep2022/Data//JetMET/run2022G_9dec2022_JetMET_Run2022G-PromptNanoAODv10_v1-v1/221209_083942/0000', '', '.*root', 2022, [], json = json)
JetMET = [JetMET_Run2022C_0, JetMET_Run2022D_0, JetMET_Run2022D_1, JetMET_Run2022E_0, JetMET_Run2022F_0, JetMET_Run2022G_0]

# ------ MuonEG dataset
MuonEG_Run2022C_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022C-PromptNanoAODv10-v1/221013_082016/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10-v1/221013_082234/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_1 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10_v1-v1/221013_082455/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022E_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022E', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/31oct2022_MuonEG_Run2022E-PromptNanoAODv10_v1-v3/221031_102255/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022F_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022F', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/data2022F_28nov2022_MuonEG_Run2022F-PromptNanoAODv10_v1-v2/221128_143326/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022G_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022G', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/run2022G_9dec2022_MuonEG_Run2022G-PromptNanoAODv10_v1-v1/221209_084128/0000', '', '.*root', 2022, [], json = json)
MuonEG = [MuonEG_Run2022C_0, MuonEG_Run2022D_0, MuonEG_Run2022D_1, MuonEG_Run2022E_0, MuonEG_Run2022F_0, MuonEG_Run2022G_0]




dataSamples_list = Muon + SingleMuon + DoubleMuon + MET + JetHT + EGamma + JetMET + MuonEG
dataSamples_toImport = dataSamples_list