# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2022-10-18 [yyyy-m-d] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
json = os.environ['CMSSW_BASE']+'/src/CMGTools/TTHAnalysis/cfg/Cert_Collisions2022_355100_357900_Golden.json'


# ------------------------ SingleMuon ------------------------- #
SingleMuon_Run2022C_v1 = kreator.makeDataComponentFromLocal('SingleMuon_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/SingleMuon/27sep2022_data_SingleMuon_Run2022C-PromptNanoAODv10-v1/221013_075910/0000', '', '.*root', 2022, [], json = json)
SingleMuon = [SingleMuon_Run2022C_v1]

# ------------------------ DoubleMuon ------------------------- #
DoubleMuon_Run2022C_v1 = kreator.makeDataComponentFromLocal('DoubleMuon_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/DoubleMuon/27sep2022_data_DoubleMuon_Run2022C-PromptNanoAODv10-v1/221013_075640/0000', '', '.*root', 2022, [], json = json)
DoubleMuon = [DoubleMuon_Run2022C_v1]

# ------------------------ EGamma ------------------------- #
EGamma_Run2022C_v2 = kreator.makeDataComponentFromLocal('EGamma_Run2022C_v2', '', '/pool/phedex/nanoAODv10/27sep2022/Data/EGamma/27sep2022_data_EGamma_Run2022C-PromptNanoAODv10-v2/221013_082717/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_v2 = kreator.makeDataComponentFromLocal('EGamma_Run2022D_v2', '', '/pool/phedex/nanoAODv10/27sep2022/Data/EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10-v2/221013_082934/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_v1_v1 = kreator.makeDataComponentFromLocal('EGamma_Run2022D_v1_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10_v1-v1/221013_083152/0000', '', '.*root', 2022, [], json = json)
EGamma = [EGamma_Run2022C_v2, EGamma_Run2022D_v2, EGamma_Run2022D_v1_v1]

# ------------------------ JetHT ------------------------- #
JetHT_Run2022C_v1 = kreator.makeDataComponentFromLocal('JetHT_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/JetHT/27sep2022_data_JetHT_Run2022C-PromptNanoAODv10-v1/221013_081051/0000', '', '.*root', 2022, [], json = json)
JetHT = [JetHT_Run2022C_v1]

# ------------------------ JetMET ------------------------- #
JetMET_Run2022C_v1 = kreator.makeDataComponentFromLocal('JetMET_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/JetMET/27sep2022_data_JetMET_Run2022C-PromptNanoAODv10-v1/221013_081310/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022D_v2 = kreator.makeDataComponentFromLocal('JetMET_Run2022D_v2', '', '/pool/phedex/nanoAODv10/27sep2022/Data/JetMET/27sep2022_data_JetMET_Run2022D-PromptNanoAODv10-v2/221013_081534/0000', '', '.*root', 2022, [], json = json)
JetMET_Run2022D_v1_v1 = kreator.makeDataComponentFromLocal('JetMET_Run2022D_v1_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/JetMET/27sep2022_data_JetMET_Run2022D-PromptNanoAODv10_v1-v1/221013_081755/0000', '', '.*root', 2022, [], json = json)
JetMET = [JetMET_Run2022C_v1, JetMET_Run2022D_v2, JetMET_Run2022D_v1_v1]

# ------------------------ MET ------------------------- #
MET_Run2022C_v1 = kreator.makeDataComponentFromLocal('MET_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/MET/27sep2022_data_MET_Run2022C-PromptNanoAODv10-v1/221013_080830/0000', '', '.*root', 2022, [], json = json)
MET = [MET_Run2022C_v1]

# ------------------------ Muon ------------------------- #
Muon_Run2022C_v1 = kreator.makeDataComponentFromLocal('Muon_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/Muon/27sep2022_data_Muon_Run2022C-PromptNanoAODv10-v1/221013_080134/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_v1 = kreator.makeDataComponentFromLocal('Muon_Run2022D_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10-v1/221013_080353/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_v1_v1 = kreator.makeDataComponentFromLocal('Muon_Run2022D_v1_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10_v1-v1/221013_080611/0000', '', '.*root', 2022, [], json = json)
Muon = [Muon_Run2022C_v1, Muon_Run2022D_v1, Muon_Run2022D_v1_v1]

# ------------------------ MuonEG ------------------------- #
MuonEG_Run2022C_v1 = kreator.makeDataComponentFromLocal('MuonEG_Run2022C_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/MuonEG/27sep2022_data_MuonEG_Run2022C-PromptNanoAODv10-v1/221013_082016/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_v1 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10-v1/221013_082234/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_v1_v1 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D_v1_v1', '', '/pool/phedex/nanoAODv10/27sep2022/Data/MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10_v1-v1/221013_082455/0000', '', '.*root', 2022, [], json = json)
MuonEG = [MuonEG_Run2022C_v1, MuonEG_Run2022D_v1, MuonEG_Run2022D_v1_v1]



#dataSamples_Runs = SingleMuon + DoubleMuon + EGamma + JetHT + JetMET + MET + Muon + MuonEG
dataSamples_Runs = MuonEG
dataSamples = dataSamples_Runs


if __name__ == "__main__":
  from CMGTools.RootTools.samples.tools import runMain
  runMain(samples, localobjs=locals())
