# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2022-10-18 [yyyy-m-d] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
# --- Drell Yan --- #
DYJetsToLL_M_10to50 = kreator.makeMCComponentFromLocal('DYJetsToLL_M_10to50', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_DYJetsToLL_M-10to50_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150028/0000', '.*root', 19317.5)
DYJetsToLL_M_50_ext1 = kreator.makeMCComponentFromLocal('DYJetsToLL_M_50_ext1', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8ext1/220926_150039/0000', '.*root', 6221.3)
DYJetsToLL_M_50_ext2 = kreator.makeMCComponentFromLocal('DYJetsToLL_M_50_ext2', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8ext2/220926_150052/0000', '.*root', 6221.3)
DYJetsToLL_M_50_ext2_part1 = kreator.makeMCComponentFromLocal('DYJetsToLL_M_50_ext2', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8ext2/220926_150052/0001', '.*root', 6221.3)
DYtoLL_NoTau = kreator.makeMCComponentFromLocal('DYtoLL_NoTau', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_DYtoLL_NoTau_CP5_13p6TeV_amcatnloFXFX-pythia8/220926_150105/0000', '.*root', 1.0)

DYs = [
  DYJetsToLL_M_10to50,
  DYJetsToLL_M_50_ext1,
  DYJetsToLL_M_50_ext2,
  DYJetsToLL_M_50_ext2_part1
]

# --- TTbar --- #
TTTo2J1L1Nu = kreator.makeMCComponentFromLocal('TTTo2J1L1Nu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TTTo2J1L1Nu_CP5_13p6TeV_powheg-pythia8/220926_150132/0000', '.*root', 405.2403)
TTTo2J1L1Nu_part1 = kreator.makeMCComponentFromLocal('TTTo2J1L1Nu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TTTo2J1L1Nu_CP5_13p6TeV_powheg-pythia8/220926_150132/0001', '.*root', 405.2403)
TTTo2L2Nu = kreator.makeMCComponentFromLocal('TTTo2L2Nu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TTTo2L2Nu_CP5_13p6TeV_powheg-pythia8/220926_150231/0000', '.*root', 97.914)

TTs = [
  TTTo2J1L1Nu,
  TTTo2J1L1Nu_part1,
  TTTo2L2Nu
]

# --- Single top --- #
TBbarQ_t = kreator.makeMCComponentFromLocal('TBbarQ_t', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TBbarQ_t-channel_4FS_CP5_13p6TeV_powheg-madspin-pythia8/220926_150120/0000', '.*root', 145.0)
TWminus = kreator.makeMCComponentFromLocal('TWminus', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TWminus_DR_AtLeastOneLepton_CP5_13p6TeV_powheg-pythia8/220926_150328/0000', '.*root', 24.2)
TbarBQ_t = kreator.makeMCComponentFromLocal('TbarBQ_t', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TbarBQ_t-channel_4FS_CP5_13p6TeV_powheg-madspin-pythia8/220926_150340/0000', '.*root', 87.2)
TbarWplus = kreator.makeMCComponentFromLocal('TbarWplus', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_TbarWplus_DR_AtLeastOneLepton_CP5_13p6TeV_powheg-pythia8/220926_150350/0000', '.*root', 24.2)

Ts = [
  TBbarQ_t,
  TWminus,
  TbarBQ_t,
  TbarWplus
]

# --- W+jets --- #
W1JetsToLNu = kreator.makeMCComponentFromLocal('W1JetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_W1JetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150401/0000', '.*root', 1.0)
W1JetsToLNu_part1 = kreator.makeMCComponentFromLocal('W1JetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_W1JetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150401/0001',  '.*root', 1.0)
W2JetsToLNu = kreator.makeMCComponentFromLocal('W2JetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_W2JetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150411/0000',  '.*root', 1.0)
W3JetsToLNu = kreator.makeMCComponentFromLocal('W3JetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_W3JetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150422/0000',  '.*root', 1.0)
W4JetsToLNu = kreator.makeMCComponentFromLocal('W4JetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_W4JetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150433/0000',  '.*root', 1.0)
WJetsToLNu = kreator.makeMCComponentFromLocal('WJetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150444/0000', '.*root', 63199.9)
WJetsToLNu_part1 = kreator.makeMCComponentFromLocal('WJetsToLNu', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/220926_150444/0001', '.*root', 63199.9)

Ws = [
 W1JetsToLNu,
 W2JetsToLNu,
 W3JetsToLNu,
 W4JetsToLNu,
 WJetsToLNu,
 WJetsToLNu_part1,
]

# --- Dibosons --- #
WW = kreator.makeMCComponentFromLocal('WW', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_WW_TuneCP5_13p6TeV-pythia8/220926_150455/0000', '.*root', 116.8)
WZ = kreator.makeMCComponentFromLocal('WZ', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_WZ_TuneCP5_13p6TeV-pythia8/220926_150505/0000', '.*root', 54.2776)
ZZ = kreator.makeMCComponentFromLocal('ZZ', '', '/pool/phedex/nanoAODv10/27sep2022/MC/26sep2022_ZZ_TuneCP5_13p6TeV-pythia8/220926_150516/0000', '.*root', 16.7)

DiBosons = [
  WW,
  WZ, 
  ZZ
]

mcSamples = DYs + Ts + TTs + DiBosons + Ws
samples = mcSamples
if __name__ == "__main__":
  from CMGTools.RootTools.samples.tools import runMain
  runMain(samples, localobjs=locals())
