# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2022-10-28 [yyyy-m-d] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
json = os.environ['CMSSW_BASE']+'/src/CMGTools/TTHAnalysis/cfg/Cert_Collisions2022_355100_357900_Golden.json'
# ------ Muon dataset
Muon_Run2022C_0 = kreator.makeDataComponentFromLocal('Muon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022C-PromptNanoAODv10-v1/221013_080134/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_0 = kreator.makeDataComponentFromLocal('Muon_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10-v1/221013_080353/0000', '', '.*root', 2022, [], json = json)
Muon_Run2022D_1 = kreator.makeDataComponentFromLocal('Muon_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//Muon/27sep2022_data_Muon_Run2022D-PromptNanoAODv10_v1-v1/221013_080611/0000', '', '.*root', 2022, [], json = json)
Muon = [Muon_Run2022C_0, Muon_Run2022D_0, Muon_Run2022D_1]

# ------ EGamma dataset
EGamma_Run2022C_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022C-PromptNanoAODv10-v2/221013_082717/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_0 = kreator.makeDataComponentFromLocal('EGamma_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10-v2/221013_082934/0000', '', '.*root', 2022, [], json = json)
EGamma_Run2022D_1 = kreator.makeDataComponentFromLocal('EGamma_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//EGamma/27sep2022_data_EGamma_Run2022D-PromptNanoAODv10_v1-v1/221013_083152/0000', '', '.*root', 2022, [], json = json)
EGamma = [EGamma_Run2022C_0, EGamma_Run2022D_0, EGamma_Run2022D_1]

# ------ SingleMuon dataset
SingleMuon_Run2022C_0 = kreator.makeDataComponentFromLocal('SingleMuon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//SingleMuon/27sep2022_data_SingleMuon_Run2022C-PromptNanoAODv10-v1/221013_075910/0000', '', '.*root', 2022, [], json = json)
SingleMuon = [SingleMuon_Run2022C_0]

# ------ DoubleMuon dataset
DoubleMuon_Run2022C_0 = kreator.makeDataComponentFromLocal('DoubleMuon_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//DoubleMuon/27sep2022_data_DoubleMuon_Run2022C-PromptNanoAODv10-v1/221013_075640/0000', '', '.*root', 2022, [], json = json)
DoubleMuon = [DoubleMuon_Run2022C_0]

# ------ MuonEG dataset
MuonEG_Run2022C_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022C', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022C-PromptNanoAODv10-v1/221013_082016/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_0 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10-v1/221013_082234/0000', '', '.*root', 2022, [], json = json)
MuonEG_Run2022D_1 = kreator.makeDataComponentFromLocal('MuonEG_Run2022D', '', '/pool/phedex/nanoAODv10/27sep2022/Data//MuonEG/27sep2022_data_MuonEG_Run2022D-PromptNanoAODv10_v1-v1/221013_082455/0000', '', '.*root', 2022, [], json = json)
MuonEG = [MuonEG_Run2022C_0, MuonEG_Run2022D_0, MuonEG_Run2022D_1]




dataSamples_list = Muon + EGamma + SingleMuon + DoubleMuon + MuonEG
dataSamples_toImport = dataSamples_list
