#!/bin/bash

## IMPORTANT REMARK: In principle, one could run all models per config/region all together,
## but this will generate a lot of jobs which are all accessing the same background ROOT file.
## This kills memory and performance. Keep in mind to split as good and effective as possible
## to optimize performance.

S="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-18_ewktrees80X_M17_signals"
T="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-25_ewkskims80X_M17_3l_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_3l_data;$S"
TT="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-25_ewkskims80X_M17_crwz_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_crwz_data;$S"
O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-06_ewk80X_approvalScans"
LUMI=35.9
#QUEUE="--pretend"
QUEUE="-q all.q"
#QUEUE=""

#QUEUE="--pretend"


## BACKGROUND + DATA
## =====================================================

#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR3 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L1(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR4 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L2(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), met_pt)" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR5 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L3(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), mT2L_3l, met_pt)" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR6 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding -R trigger triggerTau "$DATA{Triggers_sl} $MC{Triggers_sl} $FASTSIM{1}" -A sanity tigherpteta "abs(LepSel1_eta)<2.1 && abs(LepSel2_eta)<2.1 && abs(LepSel3_eta)<2.1" -A sanity tighterpt "(abs(LepSel1_pdgId)==11 && LepSel1_pt>30) || (abs(LepSel1_pdgId)==13 && LepSel1_pt>25) || (abs(LepSel2_pdgId)==11 && LepSel2_pt>30) || (abs(LepSel2_pdgId)==13 && LepSel2_pt>25) || (abs(LepSel3_pdgId)==11 && LepSel3_pt>30) || (abs(LepSel3_pdgId)==13 && LepSel3_pt>25)"' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L4(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), mT2T_3l, met_pt)" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR7 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding -R trigger triggerTau "$DATA{Triggers_sl} $MC{Triggers_sl} $FASTSIM{1}" -A sanity tigherpteta "abs(LepSel1_eta)<2.1 && abs(LepSel2_eta)<2.1 && abs(LepSel3_eta)<2.1" -A sanity tighterpt "(abs(LepSel1_pdgId)==11 && LepSel1_pt>30) || (abs(LepSel1_pdgId)==13 && LepSel1_pt>25) || (abs(LepSel2_pdgId)==11 && LepSel2_pt>30) || (abs(LepSel2_pdgId)==13 && LepSel2_pt>25) || (abs(LepSel3_pdgId)==11 && LepSel3_pt>30) || (abs(LepSel3_pdgId)==13 && LepSel3_pt>25)"' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L5(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), met_pt)" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR8 --models TChiWZ --bkgOnly --redoBkg --noRFlags --flags '-X blinding' --mca susy-ewkino/4l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig4L1(met_pt)" $QUEUE


## WINOS
## =====================================================

#### TChiWZ 
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR3 --models TChiWZ --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L1(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR4 --models TChiWZ --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L2(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##
#### TChiSlepSnu_FD
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR3 --models TChiSlepSnu_FD --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L1(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR4 --models TChiSlepSnu_FD --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L2(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##
#### TChiSlepSnu_FD_05
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR3 --models TChiSlepSnu_FD_05 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L1(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR4 --models TChiSlepSnu_FD_05 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L2(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##
#### TChiSlepSnu_FD_95
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR3 --models TChiSlepSnu_FD_95 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L1(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR4 --models TChiSlepSnu_FD_95 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L2(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' $QUEUE
##
#### TChiSlepSnu_TE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR5 --models TChiSlepSnu_TE    --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L3(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lC' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR5 --models TChiSlepSnu_TE_05 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L3(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lC' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR5 --models TChiSlepSnu_TE_95 --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L3(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lC' $QUEUE
##
### TChiSlepSnu_TD
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR6 --models TChiSlepSnu_TD --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L4(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lF' $QUEUE
##python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR7 --models TChiSlepSnu_TD --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/3l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig3L5(countTaus(3, LepSel_pdgId[0], LepSel_pdgId[1], LepSel_pdgId[2]), srMt, met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lF' $QUEUE

# Higgsinos
python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR8 --models TChiZZ4L --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/4l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig4L1(met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' $QUEUE
python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR8 --models TChiHZ   --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/4l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig4L1(met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' $QUEUE
python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SSR8 --models TChiHH   --sigOnly --noRFlags --flags '-X blinding' --mca susy-ewkino/4l/mca_forScan.txt --bins "1,0.5,1.5" --expr "SuperSig4L1(met_pt)" --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' $QUEUE

