#!/bin/bash

## IMPORTANT REMARK: In principle, one could run all models per config/region all together,
## but this will generate a lot of jobs which are all accessing the same background ROOT file.
## This kills memory and performance. Keep in mind to split as good and effective as possible
## to optimize performance.

S="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-18_ewktrees80X_M17_signals"
T="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-25_ewkskims80X_M17_3l_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_3l_data;$S"
TT="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-25_ewkskims80X_M17_crwz_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_crwz_data;$S"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-06_ewk80X_approvalScans"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-06_ewk80X_approvalScans_TE"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-13_ewk80X_postApprovalScans_pfMET"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-13_ewk80X_postApprovalScans"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-04-05_ewk80X_combinationTest"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-03-13_ewk80X_postApprovalScans_HZphysical"
O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-04-08_ewk80X_wzCorrCards_smWZasSig"

## full dataset
LUMI=35.9
BLIND="-X blinding"

## ichep dataset
#LUMI=12.9
#BLIND=""

## queue
#QUEUE="--pretend --perBin"
QUEUE="-q all.q"
#QUEUE=""



## BACKGROUND + DATA
## =====================================================

#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/3l/mca_forScan.txt $QUEUE
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" $QUEUE
#python susy-interface/scanmaker.py 3l "3lA1;3lA2;3lB;3lC;3lD;3lF" $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/3l/mca_forScan.txt $QUEUE
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/3l/mca_forScan_3lE.txt $QUEUE
#python susy-interface/scanmaker.py 4l "4lG;4lH;4lI;4lJ;4lK" $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/4l/mca_forScan.txt $QUEUE



## WINOS
## =====================================================

## TChiWH
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiWH --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --mpfr 3lC' --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lF" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb.root --frMap tauFR_data --mpfr 3lF' --check
#python susy-interface/scanmaker.py 4l "4lG" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' --check
#python susy-interface/scanmaker.py 4l "4lH" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lH' --check
#python susy-interface/scanmaker.py 4l "4lI" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lI' --check
#python susy-interface/scanmaker.py 4l "4lJ" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lJ' --check
#python susy-interface/scanmaker.py 4l "4lK" $T $O -l $LUMI -o SR --models TChiWH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lK' --check

## TChiWZ
python susy-interface/scanmaker.py crwzWZ crwz $TT $O -l $LUMI -o SR --models TChiWZ --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check 
python susy-interface/scanmaker.py 3lWZ "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiWZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check

## TChiSlepSnu_FD
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_FD --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_FD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
###
##### TChiSlepSnu_FD_05
###python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_FD_05 --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
###python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_FD_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check

## TChiSlepSnu_FD_95
###python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_FD_95 --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
###python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_FD_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check

## TChiSlepSnu_TE
###python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check

## TChiSlepSnu_TE_05
###python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check

## TChiSlepSnu_TE_95
###python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check
###python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check

## TChiSlepSnu_TD
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino_noCR.txt --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino_noCR.txt --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TD --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino_noCR.txt --check
#python susy-interface/scanmaker.py 3l "3lF" $T $O -l $LUMI -o SR --models TChiSlepSnu_TD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lF' --sys susy-ewkino/systs_ewkino_noCR.txt --check


## TE with 2lss and 3lA
## =====================================================

### TChiSlepSnu_TE
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_TE --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check
#
### TChiSlepSnu_TE_05
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_05 --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check
#
### TChiSlepSnu_TE_95
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiSlepSnu_TE_95 --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --sys susy-ewkino/systs_ewkino.txt --check

## HIGGSINOS
## =====================================================

## TChiZZ4L
##python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiZZ4L --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb  --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb  --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lF" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lF' --check
#python susy-interface/scanmaker.py 4l "4lG" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' --check --m1 100 --m2 1
#python susy-interface/scanmaker.py 4l "4lH" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lH' --check
#python susy-interface/scanmaker.py 4l "4lI" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lI' --check
#python susy-interface/scanmaker.py 4l "4lJ" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lJ' --check
#python susy-interface/scanmaker.py 4l "4lK" $T $O -l $LUMI -o SR --models TChiZZ4L --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 4lK' --check

## TChiHZ  
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiHZ --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lF" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lF' --check
#python susy-interface/scanmaker.py 4l "4lG" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' --check
#python susy-interface/scanmaker.py 4l "4lH" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lH' --check
#python susy-interface/scanmaker.py 4l "4lI" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lI' --check
#python susy-interface/scanmaker.py 4l "4lJ" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lJ' --check
#python susy-interface/scanmaker.py 4l "4lK" $T $O -l $LUMI -o SR --models TChiHZ --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lK' --check

## TChiHH  
#python susy-interface/scanmaker.py crwz crwz $TT $O -l $LUMI -o SR --models TChiHH --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpV_FL_data_comb --mpfr 2lss' --check
#python susy-interface/scanmaker.py 3l "3lA1;3lA2" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check
#python susy-interface/scanmaker.py 3l "3lB" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lB' --check
#python susy-interface/scanmaker.py 3l "3lC" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lC' --check
#python susy-interface/scanmaker.py 3l "3lD" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lE" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan_3lE.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lD' --check
#python susy-interface/scanmaker.py 3l "3lF" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_tau_EWKino_Moriond2017_36p5fb_Final.root --frMap data_ratio --mpfr 3lF' --check
#python susy-interface/scanmaker.py 4l "4lG" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lG' --check
#python susy-interface/scanmaker.py 4l "4lH" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lH' --check
#python susy-interface/scanmaker.py 4l "4lI" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lI' --check
#python susy-interface/scanmaker.py 4l "4lJ" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lJ' --check
#python susy-interface/scanmaker.py 4l "4lK" $T $O -l $LUMI -o SR --models TChiHH --mca susy-ewkino/4l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 4lK' --check






## TESTING
## =====================================================
#S="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-18_ewktrees80X_M17_signals"
#T="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-25_ewkskims80X_M17_3l_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_3l_data;$S"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-04-05_ewk80X_newScore"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-04-05_ewk80X_newScore_500_150"
#LUMI=35.9
#BLIND="-X blinding"
##QUEUE="--pretend --perBin"
#QUEUE="-q all.q"

#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/3l/mca_forScan.txt $QUEUE
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SR --models TChiWZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check --m1 200 --m2 100
#python susy-interface/scanmaker.py 3l "3lA" $T $O -l $LUMI -o SR --models TChiWZ --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb --mpfr 3lA' --check --m1 500 --m2 150






## TESTING
## =====================================================
#python susy-interface/scanmaker.py 3l 3lA $T $O -l $LUMI -o SR --models TChiWZ --bkgOnly --redoBkg --flags "$BLIND" --mca susy-ewkino/3l/mca_forScan.txt $QUEUE 
#python susy-interface/scanmaker.py 3l 3lA $T $O -l $LUMI -o SR --models TChiSlepSnu_FD --mca susy-ewkino/3l/mca_forScan.txt --flags "$BLIND" --sigOnly $QUEUE --postfix '--postfix-pred fakes_appldata*=fixFakePredictionForZeroEvts --frFile $CMSSW_BASE/src/CMGTools/TTHAnalysis/data/fakerate/fakerate_light_EWKino_Moriond2017_36p5fb.root --frMap FR_susy_wpM_FL_data_comb' --check
