#!/bin/bash

T="/mnt/t3nfs01/data01/shome/cheidegg/o/2015-11-29_ewkskims80X_M17"
O="/afs/cern.ch/user/c/cheidegg/www/heppy/2016-12-06_ewk80X_closureTest"
QUEUE="" #"-q all.q"

#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noFlags -o 3lttbar $QUEUE
python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots lep --flags '-X blinding -X filters -X trigger --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noFlags -o 3lttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots evt --flags '-X blinding -X filters -X trigger --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noFlags -o 3lttbar $QUEUE
python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noFlags -o 3ldy $QUEUE
python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots lep --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noFlags -o 3ldy $QUEUE
python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots evt --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noFlags -o 3ldy $QUEUE

