#!/bin/bash

#T="/scratch/cheidegg/Prod23Jan/"
T="/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_3l_bkg;/mnt/t3nfs01/data01/shome/cheidegg/o/2017-02-23_ewkskims80X_M17_3l_data"
O="/afs/cern.ch/user/c/cheidegg/www/heppy/2017-02-24_ewk80X_closureTest" # do NOT give a trailing /
QUEUE="" #"-q all.q"
LUMI=35.9


## light lepton closure only
## ====================================================

## ttbar
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_ttbar $QUEUE

## DY
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB" $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o light_dy $QUEUE



## tau closure only
## ====================================================

## ttbar
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_ttbar $QUEUE

## DY
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE
python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger -X met --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])"' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_dy --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -A bJetVeto genMatchLight "hasPromptLight(3, LepSel_pdgId[0], LepSel_mcUCSX[0], LepSel_pdgId[1], LepSel_mcUCSX[1], LepSel_pdgId[2], LepSel_mcUCSX[2])" -X rightcharge -X tightcharge' --bkgs "matched_dy;appl_dy" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o tau_dy $QUEUE


## both flavor closure
## ====================================================
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots evt      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lC;3lD;3lF" $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lE"         $T $O -l $LUMI --make bkgs --plots lep      --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --plotmode closure --numerator matched_ttbar --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt -e -X rightcharge -X tightcharge' --bkgs "matched_ttbar;appl_ttbar" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o mix_ttbar $QUEUE





## OLD CLOSURE TEST PLOTS

##python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o 3lttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots lep --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o 3lttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots evt --flags '-X blinding -X filters -X trigger --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_TT --ratioDen _appl_fakes_TT --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_TT;_appl_fakes_TT" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noCFlags  -o 3lttbar $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots perCateg --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noCFlags  -o 3ldy $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots lep --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt  --lspam 'Simulation' --noWeight --noCFlags  -o 3ldy $QUEUE
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE" $T $O -l 36.5 --make bkgs --plots evt --flags '-X blinding -X filters -X trigger -R met met0 "met_pt>0" --ratioYLabel "Obs./pred." --ratioNum _matched_fakes_DY --ratioDen _appl_fakes_DY --plotmode nostack --fixRatioRange --maxRatioRange 0.5 1.5 --neg --perBin --ratioOffset 0.03 --print C,png,pdf,txt' --bkgs "_matched_fakes_DY;_appl_fakes_DY" --mca susy-ewkino/3l/mca_closure.txt --plot susy-ewkino/3l/plots_closure.txt --lspam 'Simulation' --noWeight --noCFlags  -o 3ldy $QUEUE

