######## CARDS
python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polW.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polWcards --ms --asimov


python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polZ.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polZcards --ms --asimov


python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polWm.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polWmcards --ms --asimov -E chargeminus

python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polWp.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polWpcards --ms --asimov -E chargeplus


python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polZm.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polZmcards --ms --asimov -E chargeminus

python makeShapeCardsSusy.py RunII_SM_WZ/2016/mca_wz_polZp.txt RunII_SM_WZ/2016/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2016/systs_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarizationGEN/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 35.9 -o WZ16_pol --od polZpcards --ms --asimov -E chargeplus


######## PLOTS
python mcPlots.py RunII_SM_WZ/2016/mca_wz_polW.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polW_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2016/mca_wz_polZ.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polZ_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend


python mcPlots.py RunII_SM_WZ/2016/mca_wz_polWm.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polWm_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal -E chargeminus --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2016/mca_wz_polWp.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polWp_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal -E chargeplus --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2016/mca_wz_polZm.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polZm_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal -E chargeminus --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2016/mca_wz_polZp.txt RunII_SM_WZ/2016/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarizationGEN/ -F sf/t /pool/cienciasrw/HeppyTrees/RA7/nanoAODv5_2016_skimWZ//bosonPolarization/evVarFriend_{cname}.root -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc --maxRatioRange 0. 1.0 --ratioYLabel Pol/Total --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2016_v5_polZp_fix/ --showRatio -E SRWZ -l 35.9 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal -E chargeplus --notShowStatTotLegend





#PLOTS 2017
python mcPlots.py RunII_SM_WZ/2017/mca_wz_polW.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polW_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2017/mca_wz_polZ.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polZ_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2017/mca_wz_polWm.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polWm_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeminus

python mcPlots.py RunII_SM_WZ/2017/mca_wz_polWp.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polWp_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeplus

python mcPlots.py RunII_SM_WZ/2017/mca_wz_polZm.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polZm_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeminus

python mcPlots.py RunII_SM_WZ/2017/mca_wz_polZp.txt RunII_SM_WZ/2017/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2017_v5_polZp_fix/ --showRatio -E SRWZ -l 41.3 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeplus

#CARDS 2017
python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polW.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polWcards --ms --asimov

python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polZ.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaZDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polZcards --ms --asimov


python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polWp.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polWpcards --ms --asimov -E chargeplus


python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polWm.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polWmcards --ms --asimov -E chargeminus


python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polZp.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaZDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polZpcards --ms --asimov -E chargeplus

python makeShapeCardsSusy.py RunII_SM_WZ/2017/mca_wz_polZm.txt RunII_SM_WZ/2017/cuts_wzsm.txt 'cos_ThetaZDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2017/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2017/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2017,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2017,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2017,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons' --obj Events -j 32 -f -E SRWZ -l 41.3 -o WZ17_pol --od polZmcards --ms --asimov -E chargeminus

#PLOTS 2018

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polW.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polW_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polZ.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polZ_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polWm.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polWm_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeminus

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polWp.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polWp_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeplus

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polZm.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polZm_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend  -E chargeminus

python mcPlots.py RunII_SM_WZ/2018/mca_wz_polZp.txt RunII_SM_WZ/2018/cuts_wzsm.txt RunII_SM_WZ/2016/plots_wz.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt --maxRatioRange 0. 1.0 --fixRatioRange --print C,pdf,png,txt --legendWidth 0.23 --legendFontSize 0.036 --showMCError --showRatio --perBin -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f --pdir /nfs/fanae/user/carlosec/www/wz/Legacy/SMWZ_2018_v5_polZp_fix/ --showRatio -E SRWZ -l 59.8 --sP pol.* --sP flav.* --ratioNums prompt_WZ_WfL,prompt_WZ_WfR,prompt_WZ_WfO --ratioDen signal --notShowStatTotLegend -E chargeplus

#CARDS 2018

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polW.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polWcards --ms --asimov

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polZ.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaZDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polZcards --ms --asimov

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polWp.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polWpcards --ms --asimov -E chargeplus

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polWm.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polWmcards --ms --asimov -E chargeminus

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polZp.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polZpcards --ms --asimov -E chargeplus

python makeShapeCardsSusy.py RunII_SM_WZ/2018/mca_wz_polZm.txt RunII_SM_WZ/2018/cuts_wzsm.txt 'cos_ThetaWDn_HE + 2*(LepW_pdgId > 0)' '40,-1,3' RunII_SM_WZ/2018/systs_wz.txt  --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ --Fs {P}/leptonPtCorrections/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --FMCs {P}/bosonPolarization/ --FMCs {P}/bosonPolarizationGEN/ -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc -L RunII_SM_WZ/functionsWZ.cc --mcc RunII_SM_WZ/2018/mcc_triggerdefs.txt  -W '(getLeptonSF_v4(0,0,2018,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2018,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2018,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))*puWeight*bTagWeightDeepCSVT_nom' --obj Events -j 32 -f -E SRWZ -l 59.8 -o WZ18_pol --od polZmcards --ms --asimov -E chargeminus

