python mcAnalysis.py RunII_SM_WZ/2016/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2016/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 35.9  -E minusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2016/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2016/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 35.9  -E plusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2017/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2017/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2017/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 41.5 -E minusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2017/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2017/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2017/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 41.5 -E plusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2018/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2018/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2018/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 59.8 -E minusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2018/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2018/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2018/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight' --obj Events -j 32   -l 59.8 -E plusgen  -E fiducial

python mcAnalysis.py RunII_SM_WZ/2016/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2016/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc  -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))' --obj Events -j 32   -l 35.9  -E plusgen  -E fiducial -E SR

python mcAnalysis.py RunII_SM_WZ/2016/includes/mca_WZ_fiducial.txt RunII_SM_WZ/2016/cuts_total.txt --tree treeProducerSusyMultilepton -P /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_unSkimmed_estructure/ --Fs {P}/leptonPtCorrections/ --FMCs {P}/trigger_prefiring/ --Fs {P}/leptonJetReCleanerWZSM/ --Fs {P}/leptonBuilderWZSM/ --Fs {P}/trigger_2016/ --FMCs {P}/leptonMatcher/ --FMCs {P}/bTagEventWeights/ --Fs {P}/bosonPolarization/ --Fs {P}/lepgenVarsWZSM_withTaus/ -L RunII_SM_WZ/functionsWZ.cc  -L RunII_SM_WZ/functionsSF.cc -L RunII_SM_WZ/functionsMCMatch.cc  -W 'puWeight*bTagWeightDeepCSVT_nom*weight_PrefiringJets*weight_PrefiringPhotons*(getLeptonSF_v4(0,0,2016,LepSel_pt[0],LepSel_eta[0],LepSel_pdgId[0])*getLeptonSF_v4(0,0,2016,LepSel_pt[1],LepSel_eta[1],LepSel_pdgId[1])*getLeptonSF_v4(0,0,2016,LepSel_pt[2],LepSel_eta[2],LepSel_pdgId[2]))' --obj Events -j 32   -l 35.9  -E minusgen  -E fiducial -E SR


