## Lepton Matcher, only MC
python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -q batch --env oviedo -N 10000000000 -n --strictCheck --onlyMC ###DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -j 8 -N 10000000000 -n --strictCheck --onlyMC ###DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -j 8 -N 10000000000 -n --strictCheck --onlyMC ###DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -j 8 -N 10000000000 -n --strictCheck --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -j 8 -N 10000000000 -n --strictCheck --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonMatcher/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonMatcher -j 8 -N 10000000000 -n --strictCheck --onlyMC ### DONE

## Lepton Pt Corrections

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2018 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonPtCorrections/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonEnergyCorrections_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend ### DONE

## Jet and photon prefiring

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/trigger_prefiring/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m JetPhotonPrefiring_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/trigger_prefiring/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m JetPhotonPrefiring_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/trigger_prefiring/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m JetPhotonPrefiring_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/trigger_prefiring/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m JetPhotonPrefiring_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend --onlyMC ### DONE

## ReCleaner

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2016_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2017_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2018_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2016_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonPtCorrections/evVarFriend_{cname}.root  ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2017_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonPtCorrections/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWK_2018_v5  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonPtCorrections/evVarFriend_{cname}.root ### DONE


python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWKFastSim_2016_v5  -j 8 -N 10000000000 -n --strictCheck ### DONE 

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWKFastSim_2017_v5  -j 8 -N 10000000000 -n --strictCheck ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/leptonJetReCleanerEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonJetReCleanerEWKFastSim_2018_v5  -j 8 -N 10000000000 -n --strictCheck ### DONE


### Builder

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2016  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2017  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2018  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE


python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2016  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2017  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2018  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2016  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2017  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE 

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/leptonBuilderEWK_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m leptonBuilderEWK_2018  -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

## BTAG

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2016 -m eventBTagWeightDeepCSVM_2016 -m eventBTagWeightDeepCSVT_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2017 -m eventBTagWeightDeepCSVM_2017 -m eventBTagWeightDeepCSVT_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2018 -m eventBTagWeightDeepCSVM_2018 -m eventBTagWeightDeepCSVT_2018 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_skimWZ/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2016 -m eventBTagWeightDeepCSVM_2016 -m eventBTagWeightDeepCSVT_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2017 -m eventBTagWeightDeepCSVM_2017 -m eventBTagWeightDeepCSVT_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVL_2018 -m eventBTagWeightDeepCSVM_2018 -m eventBTagWeightDeepCSVT_2018 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonPtCorrections/evVarFriend_{cname}.root -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_estructure/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root --onlyMC ### DONE


python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVLFS_2016 -m eventBTagWeightDeepCSVMFS_2016 -m eventBTagWeightDeepCSVTFS_2016 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2016_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVLFS_2017 -m eventBTagWeightDeepCSVMFS_2017 -m eventBTagWeightDeepCSVTFS_2017 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2017_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

python prepareEventVariablesFriendTree.py /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/ /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/bTagEventWeights_NEWID/ --tree treeProducerSusyMultilepton --ttree Events --tra2  -I CMGTools.TTHAnalysis.tools.multilepSUSTreeProducers  -m eventBTagWeightDeepCSVLFS_2018 -m eventBTagWeightDeepCSVMFS_2018 -m eventBTagWeightDeepCSVTFS_2018 -j 8 -N 10000000000 -n --strictCheck  --pretend -F sf/t /pool/ciencias/HeppyTrees/RA7/nanoAODv5_2018_signals/leptonJetReCleanerEWK_NEWID/evVarFriend_{cname}.root ### DONE

