python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_stopTests.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/Combine/CMSSW_8_1_0/src/datacards/testStopCards/ -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'


python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll60_2016Lum  -l 35.9 -E maxMll60 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll50_2016Lum  -l 35.9 -E maxMll50 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll40_2016Lum  -l 35.9 -E maxMll40 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll30_2016Lum  -l 35.9 -E maxMll30 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll20_2016Lum  -l 35.9 -E maxMll20 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Pt30_2016Lum  -l 35.9 -E firstPt -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'



python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/NoCut_2017Lum  -l 81.0 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'


python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll60_2017Lum  -l 81.0 -E maxMll60 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll50_2017Lum  -l 81.0 -E maxMll50 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll40_2017Lum  -l 81.0 -E maxMll40 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll30_2017Lum  -l 81.0 -E maxMll30 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll20_2017Lum  -l 81.0 -E maxMll20 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Pt30_2017Lum  -l 81.0 -E firstPt -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))'







python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/NoCut_2016LumptCut  -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt


python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll60_2016LumptCut  -l 35.9 -E maxMll60 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll50_2016LumptCut  -l 35.9 -E maxMll50 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll40_2016LumptCut  -l 35.9 -E maxMll40 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll30_2016LumptCut  -l 35.9 -E maxMll30 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll20_2016LumptCut  -l 35.9 -E maxMll20 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Pt30_2016LumptCut  -l 35.9 -E firstPt -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt




python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/NoCut_2017LumptCut  -l 81.0 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt


python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll60_2017LumptCut  -l 81.0 -E maxMll60 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll50_2017LumptCut  -l 81.0 -E maxMll50 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll40_2017LumptCut  -l 81.0 -E maxMll40 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll30_2017LumptCut  -l 81.0 -E maxMll30 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Mll20_2017LumptCut  -l 81.0 -E maxMll20 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/Pt30_2017LumptCut  -l 81.0 -E firstPt -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/OLDTRIGGER_2017Lum  -l 81.0 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt -E firstPt -E trigger_OLD --mcc ./susy-ewkino/mcc_triggerdefs.txt

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan_lowpt.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3l/functionsEWK.cc --load-macro susy-ewkino/3lcorr/functionsEWKcorr.cc --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/lowpt_2017Lum  -l 81.0 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepGood_pt[iL_Mini[0]], LepGood_eta[iL_Mini[0]], LepGood_pdgId[0], 0), getLepSF(LepGood_pt[iL_Mini[1]], LepGood_eta[iL_Mini[1]], LepGood_pdgId[iL_Mini[1]], 0), getLepSF(LepGood_pt[iL_Mini[1]], LepGood_eta[iL_Mini[1]], LepGood_pdgId[iL_Mini[1]], 0))' -E lepPt -E firstPt -E trigger_NEW --mcc ./susy-ewkino/3lfor2017Tests/deltatriggers_loose.txt --load-macro ./susy-ewkino/3lfor2017Tests/functionsIdealTrigger.cc

python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3lfor2017Tests/cuts_scan.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_wzCorr.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3lfor2017Tests/functionsEWK.cc  --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L_lowpt_v2/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK_lowpt/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/CMSSW_7_4_7/DatacardsEWKino_correctedb/OLDTRIGGER_2017Lum_MtWZ  -l 81.0 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' -E lepPt -E firstPt -E trigger_OLD --mcc ./susy-ewkino/mcc_triggerdefs.txt













python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3l/cuts_ewkino.txt "SRcorr" "58,0.5,58.5" susy-ewkino/systs_like.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3lfor2017Tests/functionsEWK_WZ.cc  --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR --od /nfs/fanae/user/carlosec/Combine/CMSSW_8_1_0/src/datacards/binned_likelihood  -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' --mcc ./susy-ewkino/mcc_triggerdefs.txt


python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3l/cuts_ewkino.txt "(TMath::Log(getLikelihood(met_pt, mTL_3l, mllL_3l, htJet30j)) + 8)+(16*(htJet30j > 100) + (htJet30j > 200)*16)" "48,-0.5,48.5" susy-ewkino/systs_like.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3lfor2017Tests/functionsEWK_WZ.cc  --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 64 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR_like --od /nfs/fanae/user/carlosec/Combine/CMSSW_8_1_0/src/datacards/binned_likelihood  -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' --mcc ./susy-ewkino/mcc_triggerdefs.txt




python makeShapeCardsSusy.py ./susy-ewkino/3lfor2017Tests/mca_scan.txt ./susy-ewkino/3l/cuts_ewkino.txt "SRcorrLikev2(mllL_3l, mTL_3l, met_pt, htJet30j, TMath::Log(getLikelihoodFit(met_pt, mTL_3l, mllL_3l, htJet30j)))" "74,-0.5,73.5" susy-ewkino/systs_wzNewSR.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3lfor2017Tests/functionsEWK_WZ.cc  --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 16 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR_like --od /nfs/fanae/user/carlosec/Combine/CMSSW_8_1_0/src/datacards/likelihood_fit_Opt -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' --mcc ./susy-ewkino/mcc_triggerdefs.txt




python makeShapeCardsSusy.py ./susy-ewkino/2lss/mca_scan.txt ./susy-ewkino/3l/cuts_ewkino.txt "SRcorrLikev2(mllL_3l, mTL_3l, met_pt, htJet30j, TMath::Log(getLikelihoodFit(met_pt, mTL_3l, mllL_3l, htJet30j)))" "74,-0.5,73.5" susy-ewkino/systs_wzNewSR.txt  --bin SR_3lW -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/ -P /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig/ --tree treeProducerSusyMultilepton --load-macro susy-ewkino/3lfor2017Tests/functionsEWK_WZ.cc  --load-macro susy-ewkino/functionsSF.cc --load-macro susy-ewkino/functionsPUW.cc --s2v -f -F sf/t {P}/leptonJetReCleanerSusyEWK3L/evVarFriend_{cname}.root -F sf/t {P}/leptonBuilderEWK/evVarFriend_{cname}.root  --FFulls /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/bkg2017/bTagEventWeightFullSim3L/ --FFasts /pool/cienciasrw/userstorage/carlosec/ewkTreesfor2017Test/sig//bTagEventWeightFastSim3L/ --asimov --hardZero -j 16 --mcc ./susy-ewkino/3l/mcc_ewkino.txt -o SR_like --od /nfs/fanae/user/carlosec/Combine/CMSSW_8_1_0/src/datacards/likelihood_fit_Opt -l 35.9 -W 'puw_nInt_Moriond(nTrueInt) * leptonSF(getLepSF(LepSel_pt[0], LepSel_eta[0], LepSel_pdgId[0], 0), getLepSF(LepSel_pt[1], LepSel_eta[1], LepSel_pdgId[1], 0), getLepSF(LepSel_pt[2], LepSel_eta[2], LepSel_pdgId[2], 0))' --mcc ./susy-ewkino/mcc_triggerdefs.txt
