#!/bin/bash

#T="/mnt/t3nfs01/data01/shome/cheidegg/o/2016-07-13_ewkskims80X"
#O="/afs/cern.ch/user/c/cheidegg/www/heppy/2016-11-14_ewk80X_35fb_expectedYields"
T="/mnt/t3nfs01/data01/shome/cheidegg/o/2015-11-29_ewkskims80X_M17_MERGED"
#O="/mnt/t3nfs01/data01/shome/cheidegg/o/2016-12-07_ewk80X_fullstatus"
O="/afs/cern.ch/user/c/cheidegg/www/heppy/2016-12-07_ewk80X_fullstatus"
PLOTS="noLog"
#PLOTS="perCateg"
QUEUE="" #"-q all.q"

## data plots (data fakes)
python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots $PLOTS -o SR --flags '--perBin' $QUEUE
python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots $PLOTS -o SR --flags '--perBin' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots evt -o SR --flags '--perBin' $QUEUE
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots evt -o SR --flags '--perBin' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots lep -o SR --flags '--perBin' $QUEUE
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots lep -o SR --flags '--perBin' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt

## data plots (MC fakes)
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots $PLOTS -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" 
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots $PLOTS -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data"
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 36.5 --make data --plots $PLOTS -o SBfakes --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 36.5 --make data --plots $PLOTS -o SBfakes --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt

## data plots
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots evt -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" 
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots evt -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data"
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $O -l 17.3 --make data --plots lep -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" 
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 17.3 --make data --plots lep -o SRmc --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data"

### data/MC comparison for ICHEP part
#OO="/afs/cern.ch/user/c/cheidegg/www/heppy/2016-12-07_ewk80X_fullstatus_ICHEP"
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" $T $OO -l 12.9 --make data --plots $PLOTS -o SRmc --flags '-X blinding -A alwaystrue ichep "run<=276811" --perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" 
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $OO -l 12.9 --make data --plots $PLOTS -o SRmc --flags '-X blinding -A alwaystrue ichep "run<=276811" --perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data"
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMCOldData $OO -l 12.9 --make data --plots $PLOTS -o SRmcICHEP --flags '-X blinding -A alwaystrue ichep "run<=276811" --perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" --mca susy-ewkino/3l/mca_ewkino_ICHEP.txt 
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMCOldData $OO -l 12.9 --make data --plots $PLOTS -o SRmcICHEP --flags '-X blinding -A alwaystrue ichep "run<=276811" --perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE --mccs susy-ewkino/4l/mcc_ewkino.txt -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" --mca susy-ewkino/4l/mca_ewkino_ICHEP.txt


## compare with old MC
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 17.3 --make data --plots $PLOTS -o SRmcOldMC --flags '--perBin --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' $QUEUE -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" --mca susy-ewkino/3l/mca_ewkino_oldMC.txt 
#python susy-interface/plotmaker.py 3l "3lA;3lB;3lC;3lD;3lE;3lF" /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 36.5 --make data --plots $PLOTS -o SBfakesOldMC --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE --mca susy-ewkino/3l/mca_ewkino_oldMC.txt

## flavor separated
#python susy-interface/plotmaker.py 3l 3lA $T $O -l 36.5 --make data --plots $PLOTS -o SBfakes3e --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST  -A alwaystrue 3els "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==33"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE
#python susy-interface/plotmaker.py 3l 3lA $T $O -l 36.5 --make data --plots $PLOTS -o SBfakes3m --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST -A alwaystrue 3mus "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==39"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE
#python susy-interface/plotmaker.py 3l 3lA /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 36.5 --make data --plots $PLOTS -o SBfakesOldMC3e --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST -A alwaystrue 3els "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==33"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE --mca susy-ewkino/3l/mca_ewkino_oldMC.txt
#python susy-interface/plotmaker.py 3l 3lA /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 36.5 --make data --plots $PLOTS -o SBfakesOldMC3m --flags '--perBin -I SRevent --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST -A alwaystrue 3mus "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==39"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs;data" $QUEUE --mca susy-ewkino/3l/mca_ewkino_oldMC.txt

## flavor separated bkg only
#python susy-interface/plotmaker.py 3l 3lA $T $O -l 36.5 --make bkgs --plots $PLOTS -o SBfakes3e --flags '--perBin -I SRevent -A alwaystrue 3els "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==33"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" $QUEUE
#python susy-interface/plotmaker.py 3l 3lA $T $O -l 36.5 --make bkgs --plots $PLOTS -o SBfakes3m --flags '--perBin -I SRevent -A alwaystrue 3mus "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==39"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" $QUEUE
#python susy-interface/plotmaker.py 3l 3lA /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 36.5 --make bkgs --plots $PLOTS -o SBfakesOldMC3e --flags '--perBin -I SRevent -A alwaystrue 3els "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==33"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" $QUEUE --mca susy-ewkino/3l/mca_ewkino_oldMC.txt
#python susy-interface/plotmaker.py 3l 3lA /mnt/t3nfs01/data01/shome/cheidegg/o/ewkSkimsWithOldMC $O -l 36.5 --make bkgs --plots $PLOTS -o SBfakesOldMC3m --flags '--perBin -I SRevent -A alwaystrue 3mus "abs(LepSel_pdgId[0])+abs(LepSel_pdgId[1])+abs(LepSel_pdgId[2])==39"' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" $QUEUE --mca susy-ewkino/3l/mca_ewkino_oldMC.txt

## expected yields
#python susy-interface/plotmaker.py 3l 3lA $T $O -l 35 --make mix --plots $PLOTS -o SR --flags '-X blinding --perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" -p "sig_TChiNeuSlepSneuFD_1100_1;sig_TChiNeuSlepSneuFD_500_475" $QUEUE
#python susy-interface/plotmaker.py 3l "3lB;3lC;3lD;3lE;3lF" $T $O -l 35 --make mix --plots $PLOTS -o SR --flags '-X blinding --perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" -p "sig_TChiNeuSlepSneuTD_500_1;sig_TChiNeuSlepSneuTD_200_150" $QUEUE
#python susy-interface/plotmaker.py 3l "4lG;4lH;4lI;4lJ;4lK" $T $O -l 35 --make mix --plots $PLOTS -o SR --flags '-X blinding --perBin --plotgroup fakes_matched_DY+=fakes_matched_WW --plotgroup fakes_matched_DY+=fakes_matched_WJ --plotgroup fakes_matched_DY+=fakes_matched_TT --plotgroup fakes_matched_DY+=fakes_matched_ST' -p "fakes_matched_.*;prompt_.*;rares_.*;convs" -p "sig_TChiNeuZZ4L_400_1;sig_TChiNeuHZ_400_1;sig_TChiNeuHH_400_1" --mccs susy-ewkino/4l/mcc_ewkino.txt $QUEUE

